time time         # rospy.Time, ros::Time

uint8 vcu_EPS_Status
uint8 vcu_ACC_Status
uint8 vcu_BRK_Status
uint8 VCU1_ADCU_AliveCnt

uint8 vcu_ADMDStatus
uint8 vcu_ADReady
uint8 vcu_Override
uint8 vcu_Estop
uint8 vcu_HazardCtl
uint8 vcu_LeftTurnCtl
uint8 vcu_RightTurnCtl
uint8 vcu_LeftTurnState
uint8 vcu_RightTurnState
uint8 VCU2_ADCU_AliveCnt

float64 vcu_VS
float64 vcu_SAS_Angle
float64 vcu_LONG_ACCEL