uint32 region_index

bool name_present
string name

bool id_present
bool id_region_present
int32 id_region
int32 id

bool anchor_present
int32 anchor_lat
int32 anchor_long
bool anchor_elevation_present
int32 anchor_elevation

bool lane_width_present
int32 lane_width
bool directionality_present
int32 directionality
bool closed_path_present
bool closed_path
bool direction_present
string direction_hex
uint32 direction_bits
bool description_present
int32 description_choice
uint32 regional_count
